name: chencoey
favicon: null
layout_spectrum: 0.25416
typography_spectrum: 0.18558840220794082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262c50'
    - '#878588'
    - '#a9b5c3'
    - '#5c6582'
  brandStrength: 0.4375
  lightness: 0.11665369663387537
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
