name: chencoey
favicon: null
layout_spectrum: 0.23091364395804703
typography_spectrum: 0.18558840220794082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.12010534154251218
  lightness: 0.11665369663387537
  saturation: 0.36300851055420935
  rhythmicContrast: 0.0019840302411466837
purpose: []
